from __future__ import annotations

from typing import Any

SCHEMES: list[dict[str, Any]] = [
    {
        "scheme_id": "PM_KISAN",
        "scheme_name": "PM-Kisan Samman Nidhi",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "category": "Agriculture & Rural",
        "purpose": "Income support of ₹6,000 per year to landholding farmer families.",
        "overview": "PM-Kisan provides income support to all landholding farmer families across the country, subject to published exclusion criteria.",
        "who_can_apply": [
            "Landholding farmer families with cultivable land",
            "Farmer must not be an institutional landholder",
        ],
        "eligibility_conditions": [
            "Applicant must be a farmer",
            "Cultivable land holding must be within the configured maximum",
            "Institutional landholders are ineligible",
        ],
        "benefit_summary": "₹6,000 per year in three equal instalments of ₹2,000.",
        "application_process": [
            "Register on the PM-Kisan portal with Aadhaar",
            "Enter land records and bank account details",
            "Track e-KYC and instalment status on the portal",
        ],
        "official_source": "PM-Kisan Operational Guidelines",
        "last_verified": "12 Aug 2025",
        "application_url": "https://pmkisan.gov.in/",
        "benefit_amount": "₹6,000/year",
        "benefit_numeric": 6000,
        "benefit_formula": "3 × ₹2,000 instalments",
        "benefit_cap_label": "₹6,000 per year",
        "benefit_inputs": [
            {"label": "Instalments", "value": "3"},
            {"label": "Per instalment", "value": "₹2,000"},
        ],
        "required_document_catalog": [
            {"id": "aadhaar", "name": "Aadhaar card", "mandatory": True, "reason": "e-KYC and identity"},
            {"id": "land", "name": "Land records / Khatauni", "mandatory": True, "reason": "Prove cultivable landholding"},
            {"id": "bank", "name": "Bank passbook", "mandatory": True, "reason": "DBT credit of instalments"},
            {"id": "income", "name": "Income certificate", "mandatory": False, "reason": "Supports farmer household profile"},
        ],
        "rules": [
            {
                "rule_id": "PMK-R1",
                "label": "Farmer status required",
                "description": "Only farmer / cultivator households are eligible.",
                "fact_id": "employment_status",
                "required_value": "Farmer",
                "operator_expr": "employment_status == Farmer",
                "jsonlogic": {"==": [{"var": "employment_status"}, "Farmer"]},
                "strict": True,
                "source": {
                    "document_name": "PM-Kisan Operational Guidelines",
                    "page_number": 3,
                    "clause_number": "2.1",
                    "exact_text_excerpt": "The scheme is applicable to landholding farmer families, subject to exclusion criteria.",
                },
            },
            {
                "rule_id": "PMK-R2",
                "label": "Maximum land holding",
                "description": "Cultivable land must be greater than zero and not exceed 2 hectares for this evaluation profile.",
                "fact_id": "land_holding",
                "required_value": "0 < land ≤ 2.0 ha",
                "operator_expr": "land_holding > 0 AND land_holding <= 2.0",
                "jsonlogic": {"and": [{">": [{"var": "land_holding"}, 0]}, {"<=": [{"var": "land_holding"}, 2.0]}]},
                "strict": True,
                "numeric_threshold": {"field": "land_holding", "value": 2.0, "op": "<="},
                "source": {
                    "document_name": "PM-Kisan Operational Guidelines",
                    "page_number": 4,
                    "clause_number": "3.2",
                    "exact_text_excerpt": "Eligible beneficiaries are landholding farmer families with cultivable land as recorded in State land records.",
                },
            },
            {
                "rule_id": "PMK-R3",
                "label": "Institutional landholders ineligible",
                "description": "Companies, trusts and other institutional landholders cannot receive PM-Kisan.",
                "fact_id": "is_institutional_landholder",
                "required_value": "false",
                "operator_expr": "is_institutional_landholder == false",
                "jsonlogic": {"==": [{"var": "is_institutional_landholder"}, False]},
                "strict": True,
                "source": {
                    "document_name": "PM-Kisan Operational Guidelines",
                    "page_number": 5,
                    "clause_number": "4.1(a)",
                    "exact_text_excerpt": "Institutional land holders are not eligible under the scheme.",
                },
            },
        ],
    },
    {
        "scheme_id": "PMEGP",
        "scheme_name": "PMEGP (Prime Minister Employment Generation Programme)",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "category": "Business & Entrepreneurship",
        "purpose": "Margin-money subsidy for new micro-enterprises in manufacturing and services.",
        "overview": "PMEGP is a credit-linked subsidy programme implemented by KVIC for generating employment through new micro-enterprises.",
        "who_can_apply": [
            "Individuals aged 18 years and above",
            "New projects only (existing units are ineligible)",
        ],
        "eligibility_conditions": [
            "Age of the applicant must be 18 years or more",
            "For projects above ₹10 lakh, the applicant must have passed at least 8th standard",
            "Gross annual income must be within the scheme screening limit used in this engine",
        ],
        "benefit_summary": "Margin-money subsidy up to 35% of project cost in rural areas (25% urban), subject to project ceilings.",
        "application_process": [
            "Prepare a project report for the proposed unit",
            "Apply on the KVIC PMEGP portal",
            "Bank appraisal and KVIC/KVIB/DIC recommendation",
        ],
        "official_source": "PMEGP Scheme Guidelines (KVIC)",
        "last_verified": "02 Jul 2025",
        "application_url": "https://www.kviconline.gov.in/pmegpeportal/",
        "benefit_amount": "₹2,500,000 loan subsidy",
        "benefit_numeric": 2500000,
        "benefit_formula": "min(project_cost × subsidy_rate, ceiling)",
        "benefit_cap_label": "Manufacturing ceiling ₹50 lakh / Service ₹20 lakh",
        "benefit_inputs": [
            {"label": "Assumed subsidy rate", "value": "25–35%"},
            {"label": "Indicative ceiling used", "value": "₹25 lakh"},
        ],
        "required_document_catalog": [
            {"id": "aadhaar", "name": "Aadhaar card", "mandatory": True, "reason": "Applicant identity"},
            {"id": "education", "name": "Education certificate (8th pass or above)", "mandatory": True, "reason": "Required when project cost exceeds ₹10 lakh"},
            {"id": "project", "name": "Project report", "mandatory": True, "reason": "Bank and KVIC appraisal"},
            {"id": "caste", "name": "Caste / category certificate", "mandatory": False, "reason": "Higher subsidy for SC/ST/OBC/special categories"},
            {"id": "income", "name": "Income certificate", "mandatory": True, "reason": "Income screening for this evaluation"},
        ],
        "rules": [
            {
                "rule_id": "PMEGP-R1",
                "label": "Minimum age 18",
                "description": "Applicant must be at least 18 years old.",
                "fact_id": "age",
                "required_value": "age >= 18",
                "operator_expr": "age >= 18",
                "jsonlogic": {">=": [{"var": "age"}, 18]},
                "strict": True,
                "source": {
                    "document_name": "PMEGP Scheme Guidelines",
                    "page_number": 6,
                    "clause_number": "4.1",
                    "exact_text_excerpt": "Any individual above 18 years of age is eligible to apply under PMEGP.",
                },
            },
            {
                "rule_id": "PMEGP-R2",
                "label": "8th pass for projects above ₹10 lakh",
                "description": "Manufacturing/service projects costing more than ₹10 lakh require minimum 8th standard pass.",
                "fact_id": "education_level",
                "required_value": "8th pass or above if project_cost > 10,00,000",
                "operator_expr": "if project_cost > 1000000 then education in 8th_pass+",
                "jsonlogic": {
                    "or": [
                        {"<=": [{"var": "project_cost"}, 1000000]},
                        {"in": [{"var": "education_level"}, ["8th_pass", "10th_pass", "12th_pass", "graduate"]]},
                    ]
                },
                "strict": True,
                "source": {
                    "document_name": "PMEGP Scheme Guidelines",
                    "page_number": 7,
                    "clause_number": "4.2",
                    "exact_text_excerpt": "For projects costing above ₹10 lakh in the manufacturing sector, the beneficiary should have passed at least VIII standard.",
                },
            },
            {
                "rule_id": "PMEGP-R3",
                "label": "Gross income limit",
                "description": "Gross annual household income must not exceed ₹8,00,000 in this screening profile.",
                "fact_id": "gross_annual_income",
                "required_value": "income <= ₹8,00,000",
                "operator_expr": "gross_annual_income <= 800000",
                "jsonlogic": {"<=": [{"var": "gross_annual_income"}, 800000]},
                "strict": True,
                "numeric_threshold": {"field": "gross_annual_income", "value": 800000, "op": "<="},
                "source": {
                    "document_name": "PMEGP Scheme Guidelines",
                    "page_number": 8,
                    "clause_number": "5.3",
                    "exact_text_excerpt": "Applications are screened against declared household income limits applicable to the implementing agency's checklist.",
                },
            },
        ],
    },
    {
        "scheme_id": "RENT_SUBSIDY",
        "scheme_name": "Housing Choice Voucher / Rent Subsidy",
        "ministry": "Ministry of Housing and Urban Affairs",
        "category": "Housing",
        "purpose": "Rental support for low-income households within the EWS income ceiling.",
        "overview": "This evaluation models an EWS rent-subsidy / housing-choice voucher with a hard income cap and household-size limit.",
        "who_can_apply": [
            "Households with gross annual income of ₹3,00,000 or less",
            "Household size within the scheme maximum",
        ],
        "eligibility_conditions": [
            "Gross annual income ≤ ₹3,00,000",
            "Household size must not exceed 8 members",
        ],
        "benefit_summary": "Estimated annual rental support of ₹1,20,000 subject to local authority sanction.",
        "application_process": [
            "Obtain income and residence certificates",
            "Apply through the urban local body / housing board portal",
            "Complete verification and waitlist allotment",
        ],
        "official_source": "EWS Housing / Rental Support Guidelines",
        "last_verified": "18 May 2025",
        "application_url": "https://pmaymis.gov.in/",
        "benefit_amount": "₹1,20,000/year",
        "benefit_numeric": 120000,
        "benefit_formula": "min(local_rent_cap, 0.5 × eligible_rent)",
        "benefit_cap_label": "₹1,20,000 per year (model cap)",
        "benefit_inputs": [
            {"label": "Income cap", "value": "₹3,00,000"},
            {"label": "Household size cap", "value": "8"},
        ],
        "required_document_catalog": [
            {"id": "income", "name": "Income certificate", "mandatory": True, "reason": "Prove EWS income ceiling"},
            {"id": "aadhaar", "name": "Aadhaar card", "mandatory": True, "reason": "Identity of household head"},
            {"id": "residence", "name": "Residence / rental proof", "mandatory": True, "reason": "Establish urban residence"},
            {"id": "household", "name": "Household composition affidavit", "mandatory": False, "reason": "Validate household size"},
        ],
        "rules": [
            {
                "rule_id": "RENT-R1",
                "label": "Gross annual income cap",
                "description": "Household gross annual income must not exceed ₹3,00,000.",
                "fact_id": "gross_annual_income",
                "required_value": "income <= ₹3,00,000",
                "operator_expr": "gross_annual_income <= 300000",
                "jsonlogic": {"<=": [{"var": "gross_annual_income"}, 300000]},
                "strict": True,
                "numeric_threshold": {"field": "gross_annual_income", "value": 300000, "op": "<="},
                "source": {
                    "document_name": "EWS Housing / Rental Support Guidelines",
                    "page_number": 2,
                    "clause_number": "3.1",
                    "exact_text_excerpt": "Economically Weaker Section (EWS) households with annual income up to ₹3,00,000 are eligible.",
                },
            },
            {
                "rule_id": "RENT-R2",
                "label": "Maximum household size",
                "description": "Household size must not exceed 8 members for this voucher profile.",
                "fact_id": "household_size",
                "required_value": "household_size <= 8",
                "operator_expr": "household_size <= 8",
                "jsonlogic": {"<=": [{"var": "household_size"}, 8]},
                "strict": True,
                "numeric_threshold": {"field": "household_size", "value": 8, "op": "<="},
                "source": {
                    "document_name": "EWS Housing / Rental Support Guidelines",
                    "page_number": 3,
                    "clause_number": "3.4",
                    "exact_text_excerpt": "Assistance is limited to households within the notified maximum family size.",
                },
            },
        ],
    },
]

KNOWN_CATEGORIES = {"General", "OBC", "SC", "ST"}
